AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Default: vpc-b9d42ed3

Resources:
  MyEc2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-00a205cb8e06c3c4e
      IamInstanceProfile: !Ref MyEc2InstanceProfile
      SecurityGroupIds:
        - !Ref MyEc2HttpSecurityGroup
      UserData: !Base64
        Fn::Sub: |
          #!/bin/bash -xe
          yum install -y aws-cfn-bootstrap

          # Install the files and packages from the metadata
          /opt/aws/bin/cfn-init -v \
            --stack ${AWS::StackName} \
            --resource MyEc2 \
            --configsets install \
            --region ${AWS::Region}

          systemctl enable cfn-hup
          systemctl start cfn-hup

          # Signal the status from cfn-init
          /opt/aws/bin/cfn-signal -e $? \
            --stack ${AWS::StackName} \
            --resource MyEc2 \
            --region ${AWS::Region}
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          install: [ installHttpd ]
        installHttpd:
          packages:
            yum:
              httpd: [ ]
          services:
            sysvinit:
              httpd:
                enabled: true
                ensureRunning: true
          commands:
            init-html:
              command: echo "<h2>Hello from $(hostname) with cfn-hup!!!</h2>" > /var/www/html/index.html
          files:
            /etc/cfn/cfn-hup.conf:
              content: !Sub |
                [main]
                stack=${AWS::StackName}
                region=${AWS::Region}
                interval=1
            /etc/cfn/hooks.d/cfn-auto-reloader.conf:
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.MyEc2.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init -v \
                  --stack ${AWS::StackName} \
                  --resource MyEc2 \
                  --configsets install \
                  --region ${AWS::Region}
                runas=root
              mode: "000400"
              owner: "root"
              group: "root"
    CreationPolicy:
      ResourceSignal:
        Timeout: PT5M


  MyEc2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref MyEc2Role

  MyEc2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  MyEc2HttpSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows HTTP access
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
